version: '3.7'

services:
  auth_api:
    container_name: auth_api
    image: auth_api_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/src
    ports:
      - "9000:9000"
    depends_on:
      - auth_db

  auth_db:
    container_name: auth_db
    hostname: auth_db
    image: library/postgres:14.1

    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth
      - POSTGRES_DB=auth
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  app_pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: auth_main
