"""add_user_username

Revision ID: 141b7ce2709b
Revises: 1f1f6c5d8d5f
Create Date: 2023-08-22 15:10:11.092413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "141b7ce2709b"
down_revision = "1f1f6c5d8d5f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.String(length=320)))
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_column("user", "username")
    # ### end Alembic commands ###
